# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: VarietyProject.IrisNotch
PackageVersion: 0.2.1
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Mark9712Seto/IrisNotch/releases/download/v0.2.1/Iris.Notch_0.2.1_x64-setup.exe
  InstallerSha256: F6C1C3693238E87C35F426E6969B4D29A2625BDF70E80E44BD852583D7D12EF6
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-04
